version: '3.3'
services:
  methylation-station:
    image: sc-registry.fredhutch.org/methylation-station:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.methylation-station.rule=Host(`methylation-station.fredhutch.org`)"
        - "traefik.http.routers.methylation-station-secured.rule=Host(`methylation-station.fredhutch.org`)"
        - "traefik.http.routers.methylation-station.entrypoints=web,web-secured"
        - "traefik.http.services.methylation-station.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.methylation-station.tls=true"

networks:
  sc-swarm-net:
    external: true